### ISSUE TITLE
[BUG]: UI for title is distorted in all visualizations when added in style panel.

### ISSUE THREAD

**Issue by ruchika-narang** [opensearch-project/observability#1103]
**What is the bug?**
1. The title is distorted in the visualization panel.
2. Fixing of extra space in the dropdown of fields in color theme.

**What is the expected behavior?**
The title should be clearly visible in the visualization panel when user has added one. Also there should not be extra space in the color dropdown before the field name.

**Do you have any screenshots?**
1. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/79983862/195047391-1d8bae2f-953a-4c2a-90d0-764349e9bf58.png">
2. 
![MicrosoftTeams-image (20)](https://user-images.githubusercontent.com/79983862/195552448-9954f84a-7f48-43aa-98fc-1f8a0a6c05c4.png)

**Comment by ramneet-persistent** [comment]
Hi @mengweieric @btzeng @anirudha 
Distorted title is fixed by increasing margin-top of plot. 
For Pie chart, title is moved on right side of plot, Kindly share your inputs on this one
Refer attached video
Thanks

https://user-images.githubusercontent.com/105915936/195583176-bbd8a7e2-4aa0-40e6-a7fd-836997b14bd7.mp4

**Comment by ramneet-persistent** [comment]
Fixed in [Pull 1119 ](https://github.com/opensearch-project/observability/pull/1119)
