### ISSUE TITLE
[FEATURE]: [Visualizations] Customization of tooltip text

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#788]
As per #670 
**Current implementation**: We have config options to show, hide, and change position of tooltip on hover.
**Proposed implementation**: Add config options to change the tooltip text - show/hide info for x y z axes, display current or all values of trace.
**Applicable to chart types**: Bar chart, Line chart, Pie chart, Heatmap, Treemap, Histogram

cc: @abasatwar @spattnaik @mrunal-z

**Comment by abasatwar** [comment]
Hi @mengweieric  , Hi @btzeng 
here are few queries -
1. Do we have to implement sort order (as we can see in the UI mentioned in #670) for tooltip as it is not mentioned in the description?
2. we are unable to find any config options to change the position of tooltip on hover
and to display 'All' values of a chart in a single tooltip using plotly.js.
So let us know if you have any reference. 
3. Since we don't have solution to display all values, do we need to change `all/single/hidden`  toggle button to 
switch ui with `show /hide` option. Let us know your thoughts.
4. This is the current UI implemented .let us know if it looks good.
<img width="684" alt="Line" src="https://user-images.githubusercontent.com/78089449/176459035-a67db9b8-5294-46b3-81af-1254b88531e6.png">

cc: @anirudha , @spattnaik 


Thanks,
Amruta
