### ISSUE TITLE
[FEATURE] Coordinate Maps - Visualization and Config Options

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#886]
Hello @shankha-das

This feature involves below implementation:-

1. Add Coordinate Map as a dropdown option.
2. Create config options with two tabs: Data and Options
3. It should render a map based on the aggregate function selected by user.
@spattnaik  @abasatwar

**Comment by nidhisinghai** [comment]
reopening on dev request @ruchika-narang

**Comment by ruchika-narang** [comment]
Hey @btzeng , @mengweieric , @anirudha 

Following is the implementation of coordinate maps. It takes data from a query from where no stats are involved, because there wasn't any query returning data with latitude and longitude of the city. Also we have configured few things in the config panel.

https://user-images.githubusercontent.com/79983862/187917821-578fff3c-e0bb-4a56-9988-df5a2a250d33.mp4

Please let us know if this looks good to you or any changes are required.

Thanks,
Ruchika

**Comment by vkushwah** [comment]
Hi @mengweieric  @btzeng 

We have some queries regarding this.

1. as per the current implementation, This visualization doesn't render when stat is present in the query. this visualization required lat and long
to represent data on the map and when we query along with stat this fields do not appear. Is this the correct impementation of this map?
2. As we have started implementation of two way sync for other visualizations, how do we implement two way sync for this as 
per the current implementation.

please let us know about this.

Thanks
Vishal
