### ISSUE TITLE
[BUG]:  If there are Multiple Dimension in a search query then 'Data Configuration' panel only takes last dimension 

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#891]
**What is the bug?**
 If there are Multiple Dimension in a search query then 'Data Configuration' panel only takes last dimension

**How can one reproduce the bug?**

1. Go to Observability/Event Analytics/Explorer page
2. Put a search query as -
source = opensearch_dashboards_sample_data_logs | stats count(), max(bytes) by span(timestamp,1d), clientip, host
3. select timestamp as 'Year to date', click Refresh
4. In 'Data Configuration' Panel, click on field of Dimension 

**What is the expected behavior?**
Here we should see all the dimension as there in query, in our case timestamp, clientip and host

Actual Behavior - The dimension field only lists the last dimension whatever there in a query and other dimension go to Metric field, in our case only host

**Do you have any screenshots?**

<img width="952" alt="image" src="https://user-images.githubusercontent.com/103416937/180391976-efcdca23-ab93-45da-a8d4-fb15da2ffaeb.png">

@anirudha @mengweieric 
cc: @abasatwar @spattnaik

**Comment by abasatwar** [comment]
Hi @mengweieric  ,
According to default behavior,  it was  implemented as last filed should be dimension and others would be metrics.
And we have not changed that behavior because of `query manager ` implementation is on hold.
Let us know if we need to fix this or we can wait till `query manager` implementation is done.

cc: @rinku-kumar-psl  , @spattnaik , @anirudha 

Thanks,
Amruta

**Comment by mengweieric** [comment]
resolved.
